name: Daily News Digest

on:
  schedule:
    - cron: "0 13 * * *"  # Runs at 6AM PST (13:00 UTC)
  workflow_dispatch:      # Optional: allows manual trigger

permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CREDS_B64: ${{ secrets.CREDS_B64 }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      SHEET_ID: ${{ secrets.SHEET_ID }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scraper
        run: python rss_scraper_bot.py

      - name: Run GPT Top Article Selector
        run: python gpt_top_article_selector.py

      - name: Run Caption Generator
        run: python caption_generator.py

      - name: Run RSS Writer (latest articles)
        run: python rss_writer.py
        env:
          CREDS_B64: ${{ secrets.CREDS_B64 }}
          SHEET_ID: ${{ secrets.SHEET_ID }}

      - name: Run RSS Writer (all articles)
        run: python rss_writer.py --loadAll

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add feed.xml top_articles.json top_articles_with_captions.json latest_articles.json
          git commit -m "🔁 Auto update for $(date '+%Y-%m-%d')" || echo "No changes to commit"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
