name: Regenerate RSS

on:
  workflow_dispatch:  # This is what your dashboard triggers!

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rebuild RSS feed
        run: python rss_writer.py

      - name: Commit and push feed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add feed.xml
          git commit -m "♻️ Auto-regenerated RSS feed"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
